spring:
  datasource:
    # url: "jdbc:h2:mem:testdb"   --- in memory
    url: "jdbc:h2:file:~/data/demo"   # file storage
    driverClassName: org.h2.Driver
    username: sa
    password:

jpa:
  show-sql: true
  hibernate.ddl-auto: update
  database-platform: org.hibernate.dialect.H2Dialect